spring:
  application:
    name: blood-sample-management-api
  datasource:
    username: root
    password: Pavan@123
    url: jdbc:mysql://localhost:3306/bsm_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true